### ISSUE TITLE
Same as English - how can this run Kalliope? No command in root

### ISSUE THREAD

**Issue by scargill** [kalliope-project/kalliope_starter_fr#1]
There isn't a command anything like Kalliope in the root of this download.

**Comment by Sispheor** [comment]
Please follow the installation documentation and come back here :)

**Comment by Sispheor** [comment]
[Here is the installation documentation](https://github.com/kalliope-project/kalliope/blob/master/Docs/installation.md).

**Comment by scargill** [comment]
Trying method 2…..

 Got the code 
Changed directory
Installing..

This is on a clean Raspberry Pi 2 – nothing else on it but fully up to date – latest version of Raspbian.

 

Got warnings – that’s ok – but ERRORS to 

warning: no previously-included files found matching '.travis.yml'

warning: no previously-included files found matching 'dev-requirements.txt'

no previously-included directories found matching 'docs/_build'

no previously-included directories found matching 'tasks'

 setuptools_scm functionality is degraded

  File "build/bdist.linux-armv7l/egg/apscheduler/executors/base_py3.py", line 12

    async def run_coroutine_job(job, jobstore_alias, run_times, logger_name):

            ^

SyntaxError: invalid syntax

 

  File "/usr/local/lib/python2.7/dist-packages/APScheduler-3.3.0-py2.7.egg/apscheduler/executors/base_py3.py", line 12

    async def run_coroutine_job(job, jobstore_alias, run_times, logger_name):

            ^

SyntaxError: invalid syntax

 

Adding APScheduler 3.3.0 to easy-install.pth file

 

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2195, in load

    raise ImportError("%r has no %r attribute" % (entry, attr))

ImportError: <module 'setuptools.dist' from '/usr/lib/python2.7/dist-packages/setuptools/dist.pyc'> has no 'check_specifier' attribute

**Comment by scargill** [comment]
Used method 2 in these docs – see other email – errors on a clean Raspberry Pi 2.

**Comment by scargill** [comment]
If this can be made to work – what I’d REALLY like to do is get it working on one of the cheaper boards because comparing to an Amazon Dot, Raspberry PI + mic + case + power comes to more than the cost of the ready built DOT.


An Orange PI ZERO on the other hand is under £10 and just as powerful…

But I want to test on pi first…

**Comment by scargill** [comment]
Sure enough – after those errors..

 

NEXT instruction “rec test.wav” 

 

There is no REC.

 

pi@raspberrypi:~/kalliope $ rec test.wav

bash: rec: command not found

pi@raspberrypi:~/kalliope $

**Comment by Sispheor** [comment]
I think it will not work on a Rpi Zero. Did you follow the [Rpi installation doc](https://github.com/kalliope-project/kalliope/blob/master/Docs/installation/raspbian_jessie.md)?

**Comment by scargill** [comment]
And just to confirm..

 

pi@raspberrypi:~/kalliope $ kalliope start

Traceback (most recent call last):

  File "/usr/local/bin/kalliope", line 5, in <module>

    from pkg_resources import load_entry_point

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>

    working_set = WorkingSet._build_master()

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master

    ws.require(__requires__)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require

    needed = self.resolve(parse_requirements(requirements))

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve

    raise DistributionNotFound(req)

pkg_resources.DistributionNotFound: mock==2.0.0

pi@raspberrypi:~/kalliope $

**Comment by Sispheor** [comment]
You need to follow the first part of the doc (Prerequisites).

**Comment by scargill** [comment]
Doing that now

**Comment by scargill** [comment]
Not a Raspberry Pi Zero – it’s a Raspberry Pi 2.

 

Doing pre-requisites

Method 2 - Manual setup using sources

Clone the project:

git clone https://github.com/kalliope-project/kalliope.git

cd kalliope

Install the project:

sudo python setup.py install

 

 

Here is the output – full of failures – I am on Et

**Comment by Sispheor** [comment]
You still have problems even after followed the full install process? Can you give me the output? What is the part that stuck? the setup.py?

**Comment by scargill** [comment]
Hmm,

 

Even though I have identical settings to yours – with a small black USB mic plugged in and speakers… I can do a recording – but nothing comes out on playback with mplayer.

 

I have used advanced settings to ensure output comes to 3.5mm jack.

 

Spotted that on mine – the speakers are on device zero. Rebooted, made the change to the file .asoundrc

 

pcm.!default {

   type asym

   playback.pcm {

     type plug

     slave.pcm "hw:0,0"

   }

   capture.pcm {

     type plug

     slave.pcm "hw:1,0"

   }

}

 

Rebooted with no hdmi lead…

Started the daemon – made a recording – played it back – nothing….

**Comment by scargill** [comment]
FINALLY – based on these instructions..

 

 

https://github.com/kalliope-project/kalliope/blob/master/Docs/installation/raspbian_jessie.md

 

I can now get decent audio in and decent audio out… 

 

HOWEVER again following the instructions – I have to use 

 

arecord -D plughw:2,0 -f S16_LE -c2 -r44100 test.wav

mplayer -ao alsa:device=hw=1,0 test.wav

 

Even after talking the HDMI lead out….

 

Using this… for asoundRC

 

pcm.!default {

   type hw

   playback.pcm {

     type hw

     slave.pcm "hw:1,0"

   }

   capture.pcm {

     type plug

     slave.pcm "hw:2,0"

   }

}

 

And restarting…

sudo /etc/init.d/alsa-utils restart

 

I STILL cannot get to the point where the simple

 

Rec test.wav

And

Mplayer test.wav will work!!!!

**Comment by Sispheor** [comment]
Can you give me the output of `aplay -l` and `arecord -l`?

**Comment by scargill** [comment]
pi@raspberrypi:~ $ arecord -l

**** List of CAPTURE Hardware Devices ****

card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 2: NW1000 [Brother NW-1000], device 0: USB Audio [USB Audio]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

pi@raspberrypi:~ $

 

 

aplay -l

 

pi@raspberrypi:~ $ aplay -l

**** List of PLAYBACK Hardware Devices ****

card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]

  Subdevices: 8/8

  Subdevice #0: subdevice #0

  Subdevice #1: subdevice #1

  Subdevice #2: subdevice #2

  Subdevice #3: subdevice #3

  Subdevice #4: subdevice #4

  Subdevice #5: subdevice #5

  Subdevice #6: subdevice #6

  Subdevice #7: subdevice #7

card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]

  Subdevices: 1/1

  Subdevice #0: subdevice #0

pi@raspberrypi:~ $

 

 

As you can see I’m using device 2 for recording (a usb camera) and device 1 for playback – they work GREAT -  the reason for this is that the little USB box for both recording and playback seems to need a self-powered microphone – ie. The normal electret produces nothing.  Anyway this works…

 

But this LOOKS right to me??

 

pcm.!default {

   type hw

   playback.pcm {

     type hw

     slave.pcm "hw:1,0"

   }

   capture.pcm {

     type plug

     slave.pcm "hw:2,0"

   }

}

**Comment by Sispheor** [comment]
I think it should be 

```
pcm.!default {
   type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,1"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:2,0"
   }
}
```

The bcm2835 ALSA card (where the jack is connected is on the card 0 and device 1.

**Comment by Sispheor** [comment]
BTW, you should edit your ticket in Github interface, because via email you leave a lot of other lines from the content of the email itself. It's heavy :)

**Comment by scargill** [comment]
No – it’s the USB device – works a treat with the commands I gave you earlier… 1,0 and 2,0

**Comment by Sispheor** [comment]
Can you come on Gitter pls?

**Comment by scargill** [comment]
sure

**Comment by scargill** [comment]
Clarify – I have TWO usb devices in – one – the camera is acting as a microphone – and the other – that little USB audio card – is acting as output.   When I tried to use the internal output of the PI the sound was awful -  and I assume that is not a good start -  so with those two USB devices sound is fine – but the mplayer and record don’t seem to be taking any notice of that file..

**Comment by Sispheor** [comment]
Peter, we've fixed the installation on the last Raspbian image and a lot of bugs in the last release. If you want to give a shot. 
I close the issue.
